version: '3'

services:
  budgetbot:
    build: .
    container_name: budgetbot-container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Persist user data
      - ./user_data:/app/user_data 