#!/usr/bin/env python3
"""File-per-task kanban for BudgetBot.

Tasks live in docs/tasks/T-NNN-slug.md (YAML-ish frontmatter + markdown body).
BOARD.md is generated — never edit it by hand.

Also provides Claude Code hook entrypoints (hook-session-start,
hook-post-tool-use, hook-stop). Hooks fail open: any unexpected error
exits 0 so a tracker bug can never break a session. stdlib only.
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import date, datetime, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TASKS_DIR = os.path.join(ROOT, "docs", "tasks")
ARCHIVE_DIR = os.path.join(TASKS_DIR, "archive")
BOARD_PATH = os.path.join(TASKS_DIR, "BOARD.md")
STATE_DIR = os.path.join(ROOT, ".claude", "hooks-state")

STATUSES = ["backlog", "todo", "doing", "review", "done"]
TYPES = ["bug", "feature", "refactor", "ops", "docs"]
AREAS = ["bot", "domain", "infra", "db", "deploy", "obs"]
PRIORITIES = ["p0", "p1", "p2", "p3"]
REQUIRED = ["id", "title", "status", "type", "area", "priority", "created", "updated"]
FIELD_ORDER = ["id", "title", "status", "type", "area", "priority",
               "deps", "tags", "blocked", "created", "updated"]
LIST_FIELDS = {"deps", "tags"}

CODE_DIRS = ("src/", "domain/", "infrastructure/", "shared/", "scripts/", "tests/")
EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
DOING_WIP_LIMIT = 2
BOARD_DONE_SHOWN = 10
ARCHIVE_AFTER_DAYS = 30

GENERATED_HEADER = ("<!-- GENERATED by scripts/tasks.py — do not edit. "
                    "Edit docs/tasks/T-*.md and run `python3 scripts/tasks.py board`. -->")


# ---------- frontmatter ----------

def parse_frontmatter(text, path="<str>"):
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing frontmatter opening '---'")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise ValueError(f"{path}: missing frontmatter closing '---'")
    meta = {}
    for raw in lines[1:end]:
        if not raw.strip():
            continue
        if ":" not in raw:
            raise ValueError(f"{path}: bad frontmatter line: {raw!r}")
        key, _, value = raw.partition(":")
        key = key.strip()
        value = re.sub(r"\s+#\s.*$", "", value).strip()
        if key in LIST_FIELDS:
            if not (value.startswith("[") and value.endswith("]")):
                raise ValueError(f"{path}: field '{key}' must be a [list]")
            items = [v.strip().strip("'\"") for v in value[1:-1].split(",")]
            meta[key] = [v for v in items if v]
        else:
            meta[key] = value.strip("'\"")
    body = "\n".join(lines[end + 1:])
    return meta, body


def serialize(meta, body):
    out = ["---"]
    for key in FIELD_ORDER:
        if key not in meta:
            continue
        value = meta[key]
        if key in LIST_FIELDS:
            out.append(f"{key}: [{', '.join(value)}]")
        else:
            out.append(f"{key}: {value}")
    out.append("---")
    return "\n".join(out) + "\n" + body


def atomic_write(path, content):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
    os.replace(tmp, path)


# ---------- task loading ----------

def task_files(include_archive=False):
    dirs = [TASKS_DIR] + ([ARCHIVE_DIR] if include_archive else [])
    files = []
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if name.startswith("T-") and name.endswith(".md"):
                files.append(os.path.join(d, name))
    return files


def load_tasks(include_archive=False):
    tasks, errors = [], []
    for path in task_files(include_archive):
        try:
            with open(path) as f:
                text = f.read()
            meta, body = parse_frontmatter(text, os.path.relpath(path, ROOT))
            meta.setdefault("deps", [])
            meta.setdefault("tags", [])
            meta.setdefault("blocked", "")
            tasks.append({"meta": meta, "body": body, "path": path,
                          "archived": os.path.dirname(path) == ARCHIVE_DIR})
        except ValueError as e:
            errors.append(str(e))
    return tasks, errors


def find_task(tasks, task_id):
    for t in tasks:
        if t["meta"].get("id") == task_id:
            return t
    return None


def save_task(task):
    task["meta"]["updated"] = str(date.today())
    atomic_write(task["path"], serialize(task["meta"], task["body"]))


def append_log(task, message):
    if "## Log" not in task["body"]:
        task["body"] = task["body"].rstrip("\n") + "\n\n## Log\n"
    task["body"] = task["body"].rstrip("\n") + f"\n- {date.today()} {message}\n"


# ---------- validation ----------

def validate_task(task):
    errors = []
    meta = task["meta"]
    rel = os.path.relpath(task["path"], ROOT)
    for field in REQUIRED:
        if not meta.get(field):
            errors.append(f"{rel}: missing required field '{field}'")
    tid = meta.get("id", "")
    if tid and not re.fullmatch(r"T-\d{3,}", tid):
        errors.append(f"{rel}: id '{tid}' does not match T-NNN")
    if tid and not os.path.basename(task["path"]).startswith(tid + "-"):
        errors.append(f"{rel}: filename does not start with '{tid}-'")
    for field, vocab in [("status", STATUSES), ("type", TYPES),
                         ("area", AREAS), ("priority", PRIORITIES)]:
        val = meta.get(field)
        if val and val not in vocab:
            errors.append(f"{rel}: {field} '{val}' not in {vocab}")
    for field in ("created", "updated"):
        val = meta.get(field, "")
        if val and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", val):
            errors.append(f"{rel}: {field} '{val}' is not YYYY-MM-DD")
    return errors


def validate_all(tasks, parse_errors):
    errors = list(parse_errors)
    warnings = []
    ids = {}
    for t in tasks:
        errors.extend(validate_task(t))
        tid = t["meta"].get("id")
        if tid:
            ids.setdefault(tid, []).append(os.path.relpath(t["path"], ROOT))
    for tid, paths in ids.items():
        if len(paths) > 1:
            errors.append(f"duplicate id {tid}: {', '.join(paths)}")
    known = set(ids)
    graph = {}
    for t in tasks:
        tid = t["meta"].get("id")
        deps = t["meta"].get("deps", [])
        graph[tid] = deps
        for dep in deps:
            if dep not in known:
                errors.append(f"{tid}: dep '{dep}' does not exist")

    visiting, done_visit = set(), set()

    def has_cycle(node, path):
        if node in done_visit or node not in graph:
            return None
        if node in visiting:
            return path + [node]
        visiting.add(node)
        for dep in graph.get(node, []):
            cycle = has_cycle(dep, path + [node])
            if cycle:
                return cycle
        visiting.discard(node)
        done_visit.add(node)
        return None

    for tid in graph:
        cycle = has_cycle(tid, [])
        if cycle:
            errors.append(f"dependency cycle: {' -> '.join(cycle)}")
            break

    doing = [t["meta"]["id"] for t in tasks
             if t["meta"].get("status") == "doing" and not t["archived"]]
    if len(doing) > DOING_WIP_LIMIT:
        warnings.append(f"{len(doing)} tasks in 'doing' ({', '.join(doing)}) — "
                        f"WIP limit is {DOING_WIP_LIMIT}, consider parking some")
    return errors, warnings


# ---------- board ----------

def last_log_line(task):
    lines = [l for l in task["body"].split("\n") if l.startswith("- ")]
    in_log = False
    last = ""
    for line in task["body"].split("\n"):
        if line.startswith("## "):
            in_log = line.strip() == "## Log"
        elif in_log and line.startswith("- "):
            last = line[2:].strip()
    return last


def sort_key(task):
    meta = task["meta"]
    return (PRIORITIES.index(meta.get("priority", "p3")), meta.get("id", ""))


def unmet_deps(task, by_id):
    unmet = []
    for dep in task["meta"].get("deps", []):
        dep_task = by_id.get(dep)
        if dep_task is None or dep_task["meta"].get("status") != "done":
            unmet.append(dep)
    return unmet


def task_line(task, by_id, with_log=False):
    meta = task["meta"]
    line = (f"- **{meta['id']}** `{meta.get('priority', '?')}/"
            f"{meta.get('type', '?')}/{meta.get('area', '?')}` {meta.get('title', '')}")
    waiting = unmet_deps(task, by_id)
    if waiting:
        line += f" _(waiting: {', '.join(waiting)})_"
    if meta.get("blocked"):
        line += f" ⛔ {meta['blocked']}"
    if with_log:
        log = last_log_line(task)
        if log:
            line += f" — last: {log}"
    return line


def render_board(tasks):
    active = [t for t in tasks if not t["archived"]]
    by_id = {t["meta"]["id"]: t for t in tasks if t["meta"].get("id")}
    out = [GENERATED_HEADER, "", "# Task Board", "",
           f"Updated: {date.today()} · see docs/ROADMAP.md for milestones", ""]
    for status in ["doing", "review", "todo", "backlog"]:
        group = sorted([t for t in active if t["meta"].get("status") == status],
                       key=sort_key)
        out.append(f"## {status.capitalize()} ({len(group)})")
        out.extend(task_line(t, by_id, with_log=(status in ("doing", "review")))
                   for t in group)
        if not group:
            out.append("_empty_")
        out.append("")
    done = sorted([t for t in active if t["meta"].get("status") == "done"],
                  key=lambda t: t["meta"].get("updated", ""), reverse=True)
    out.append(f"## Done (last {BOARD_DONE_SHOWN} of {len(done)})")
    out.extend(task_line(t, by_id) for t in done[:BOARD_DONE_SHOWN])
    if not done:
        out.append("_empty_")
    out.append("")
    return "\n".join(out)


def write_board(tasks):
    os.makedirs(TASKS_DIR, exist_ok=True)
    atomic_write(BOARD_PATH, render_board(tasks))


def next_tasks(tasks):
    by_id = {t["meta"]["id"]: t for t in tasks if t["meta"].get("id")}
    ready = [t for t in tasks
             if not t["archived"]
             and t["meta"].get("status") == "todo"
             and not t["meta"].get("blocked")
             and not unmet_deps(t, by_id)]
    return sorted(ready, key=sort_key), by_id


# ---------- CLI commands ----------

def slugify(title):
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug[:40].rstrip("-") or "task"


def cmd_new(args):
    tasks, _ = load_tasks(include_archive=True)
    max_num = 0
    for t in tasks:
        m = re.fullmatch(r"T-(\d+)", t["meta"].get("id", ""))
        if m:
            max_num = max(max_num, int(m.group(1)))
    tid = f"T-{max_num + 1:03d}"
    today = str(date.today())
    meta = {"id": tid, "title": args.title, "status": args.status,
            "type": args.type, "area": args.area, "priority": args.priority,
            "deps": [d for d in (args.deps or "").split(",") if d],
            "tags": [t for t in (args.tags or "").split(",") if t],
            "blocked": args.blocked or "", "created": today, "updated": today}
    body = (f"\n## Context\n{args.context or 'TODO'}\n"
            f"\n## Acceptance\n- [ ] TODO\n"
            f"\n## Log\n- {today} created\n")
    path = os.path.join(TASKS_DIR, f"{tid}-{slugify(args.title)}.md")
    os.makedirs(TASKS_DIR, exist_ok=True)
    atomic_write(path, serialize(meta, body))
    tasks, parse_errors = load_tasks(include_archive=True)
    write_board(tasks)
    print(f"created {os.path.relpath(path, ROOT)}")


def _transition(task_id, new_status, log_msg):
    tasks, _ = load_tasks(include_archive=True)
    task = find_task(tasks, task_id)
    if task is None:
        print(f"error: no task {task_id}", file=sys.stderr)
        return 1
    task["meta"]["status"] = new_status
    append_log(task, log_msg)
    save_task(task)
    write_board(tasks)
    print(f"{task_id} -> {new_status}")
    return 0


def cmd_start(args):
    return _transition(args.id, "doing", "started")


def cmd_review(args):
    rc = _transition(args.id, "review", "moved to review")
    if rc == 0:
        print("review gate: generate a manual-testing checklist per "
              ".claude/instructions/post_implementation_testing.md and append it "
              "under a '## Testing' section in the task file.")
    return rc


def cmd_done(args):
    tasks, _ = load_tasks(include_archive=True)
    task = find_task(tasks, args.id)
    if task is None:
        print(f"error: no task {args.id}", file=sys.stderr)
        return 1
    unchecked = len(re.findall(r"^- \[ \]", task["body"], flags=re.M))
    rc = _transition(args.id, "done", "done")
    if rc == 0 and unchecked:
        print(f"warning: {unchecked} unchecked checkbox(es) remain in {args.id} — "
              f"verify they are intentionally skipped")
    return rc


def cmd_log(args):
    tasks, _ = load_tasks(include_archive=True)
    task = find_task(tasks, args.id)
    if task is None:
        print(f"error: no task {args.id}", file=sys.stderr)
        return 1
    append_log(task, args.message)
    save_task(task)
    write_board(tasks)
    print(f"logged to {args.id}")
    return 0


def cmd_board(args):
    tasks, parse_errors = load_tasks(include_archive=True)
    if parse_errors:
        for e in parse_errors:
            print(f"error: {e}", file=sys.stderr)
        return 1
    write_board(tasks)
    print(f"rendered {os.path.relpath(BOARD_PATH, ROOT)}")
    return 0


def cmd_validate(args):
    tasks, parse_errors = load_tasks(include_archive=True)
    errors, warnings = validate_all(tasks, parse_errors)
    for w in warnings:
        print(f"warning: {w}")
    for e in errors:
        print(f"error: {e}", file=sys.stderr)
    if errors:
        return 1
    print(f"ok: {len(tasks)} tasks valid")
    return 0


def cmd_next(args):
    tasks, _ = load_tasks(include_archive=True)
    ready, by_id = next_tasks(tasks)
    if not ready:
        print("no unblocked todo tasks — check backlog or blocked items")
        return 0
    for t in ready[:args.count]:
        print(task_line(t, by_id))
    return 0


def cmd_archive(args):
    tasks, _ = load_tasks()
    cutoff = date.today() - timedelta(days=ARCHIVE_AFTER_DAYS)
    moved = 0
    for t in tasks:
        meta = t["meta"]
        if meta.get("status") != "done" or t["archived"]:
            continue
        try:
            updated = datetime.strptime(meta.get("updated", ""), "%Y-%m-%d").date()
        except ValueError:
            continue
        if updated <= cutoff:
            os.makedirs(ARCHIVE_DIR, exist_ok=True)
            os.replace(t["path"], os.path.join(ARCHIVE_DIR, os.path.basename(t["path"])))
            moved += 1
    tasks, _ = load_tasks(include_archive=True)
    write_board(tasks)
    print(f"archived {moved} task(s)")
    return 0


# ---------- hook entrypoints ----------

def read_stdin_json():
    try:
        return json.load(sys.stdin)
    except Exception:
        return {}


def board_is_stale():
    if not os.path.exists(BOARD_PATH):
        return True
    board_mtime = os.path.getmtime(BOARD_PATH)
    return any(os.path.getmtime(p) > board_mtime for p in task_files(True))


def hook_session_start(args):
    read_stdin_json()
    if not os.path.isdir(TASKS_DIR):
        return 0
    tasks, parse_errors = load_tasks(include_archive=True)
    if board_is_stale() and not parse_errors:
        write_board(tasks)
    errors, warnings = validate_all(tasks, parse_errors)
    by_id = {t["meta"]["id"]: t for t in tasks if t["meta"].get("id")}
    doing = sorted([t for t in tasks if not t["archived"]
                    and t["meta"].get("status") == "doing"], key=sort_key)
    review = sorted([t for t in tasks if not t["archived"]
                     and t["meta"].get("status") == "review"], key=sort_key)
    ready, _ = next_tasks(tasks)

    out = ["## Task board brief (docs/tasks/BOARD.md · python3 scripts/tasks.py --help)"]
    if doing:
        out.append("Doing:")
        out.extend(task_line(t, by_id, with_log=True) for t in doing[:5])
    if review:
        out.append("In review (needs testing checklist):")
        out.extend(task_line(t, by_id) for t in review[:3])
    if ready:
        out.append("Next up:")
        out.extend(task_line(t, by_id) for t in ready[:3])
    if not (doing or review or ready):
        out.append("Board is idle — no doing/review/unblocked-todo tasks.")
    for w in warnings[:3]:
        out.append(f"⚠ {w}")
    for e in errors[:5]:
        out.append(f"✗ validation: {e}")
    out.append("Rule: when working on a task, log progress as checkboxes flip "
               "(python3 scripts/tasks.py log <id> \"msg\").")
    print("\n".join(out[:30]))
    return 0


def hook_post_tool_use(args):
    data = read_stdin_json()
    file_path = (data.get("tool_input") or {}).get("file_path") or ""
    if not file_path:
        return 0
    abs_path = os.path.abspath(file_path)
    if not abs_path.startswith(TASKS_DIR + os.sep):
        return 0
    if abs_path == BOARD_PATH:
        print("BOARD.md is generated — revert this edit and change the task file "
              "(docs/tasks/T-*.md) instead, then run: python3 scripts/tasks.py board",
              file=sys.stderr)
        return 2
    name = os.path.basename(abs_path)
    if not (name.startswith("T-") and name.endswith(".md")):
        return 0
    try:
        with open(abs_path) as f:
            meta, body = parse_frontmatter(f.read(), name)
        task = {"meta": meta, "body": body, "path": abs_path,
                "archived": os.path.dirname(abs_path) == ARCHIVE_DIR}
        errors = validate_task(task)
    except (ValueError, OSError) as e:
        errors = [str(e)]
    if errors:
        print("task file invalid — fix the frontmatter:\n" + "\n".join(errors),
              file=sys.stderr)
        return 2
    task["meta"].setdefault("deps", [])
    task["meta"].setdefault("tags", [])
    task["meta"].setdefault("blocked", "")
    save_task(task)  # touches 'updated'
    tasks, parse_errors = load_tasks(include_archive=True)
    if not parse_errors:
        write_board(tasks)
    return 0


def collect_transcript_activity(transcript_path):
    """Return (edited_paths, task_cli_used) from a session transcript JSONL."""
    edited, task_cli = set(), False

    def walk(node):
        nonlocal task_cli
        if isinstance(node, dict):
            if node.get("type") == "tool_use":
                name = node.get("name", "")
                tool_input = node.get("input") or {}
                if name in EDIT_TOOLS and tool_input.get("file_path"):
                    edited.add(tool_input["file_path"])
                if name == "Bash":
                    cmd = tool_input.get("command", "")
                    if re.search(r"tasks\.py\s+(new|start|review|done|log|archive)\b", cmd):
                        task_cli = True
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    with open(transcript_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                walk(json.loads(line))
            except json.JSONDecodeError:
                continue
    return edited, task_cli


def hook_stop(args):
    data = read_stdin_json()
    if data.get("stop_hook_active"):
        return 0
    session_id = re.sub(r"[^A-Za-z0-9_-]", "", str(data.get("session_id") or "unknown"))
    sentinel = os.path.join(STATE_DIR, f"nudged-{session_id}")
    if os.path.exists(sentinel):
        return 0
    transcript_path = data.get("transcript_path") or ""
    if not os.path.isfile(transcript_path):
        return 0
    edited, task_cli_used = collect_transcript_activity(transcript_path)
    if task_cli_used:
        return 0
    code_touched, task_touched = False, False
    for path in edited:
        rel = os.path.relpath(os.path.abspath(path), ROOT)
        if rel.startswith(".."):
            continue
        if rel.startswith("docs/tasks/") and os.path.basename(rel).startswith("T-"):
            task_touched = True
        elif rel.startswith(CODE_DIRS):
            code_touched = True
    if not code_touched or task_touched:
        return 0

    tasks, _ = load_tasks()
    doing = [t["meta"]["id"] for t in tasks if t["meta"].get("status") == "doing"]
    os.makedirs(STATE_DIR, exist_ok=True)
    now = time.time()
    for name in os.listdir(STATE_DIR):
        p = os.path.join(STATE_DIR, name)
        if now - os.path.getmtime(p) > 86400:
            os.remove(p)
    with open(sentinel, "w") as f:
        f.write(str(now))

    if doing:
        print(f"Task tracker: code was changed this session but no task file was "
              f"updated. Active task(s): {', '.join(doing)}. Update the log "
              f"(python3 scripts/tasks.py log {doing[0]} \"what changed\") and/or "
              f"move status (done/review), then finish. This check fires once per "
              f"session.", file=sys.stderr)
    else:
        print("Task tracker: code was changed this session but no task is in "
              "'doing' and no task file was updated. Either create/start a task "
              "for this work (python3 scripts/tasks.py new --title \"...\" "
              "--type ... --area ... && tasks.py start <id>), log it against an "
              "existing task, or — if the change is trivial — state that and "
              "finish. This check fires once per session.", file=sys.stderr)
    return 2


# ---------- main ----------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("new", help="create a task")
    p.add_argument("--title", required=True)
    p.add_argument("--type", required=True, choices=TYPES)
    p.add_argument("--area", required=True, choices=AREAS)
    p.add_argument("--priority", default="p2", choices=PRIORITIES)
    p.add_argument("--status", default="todo", choices=STATUSES)
    p.add_argument("--deps", help="comma-separated task ids")
    p.add_argument("--tags", help="comma-separated tags")
    p.add_argument("--blocked", help="external blocker reason")
    p.add_argument("--context", help="context paragraph")
    p.set_defaults(func=cmd_new)

    for name, func, help_text in [("start", cmd_start, "todo -> doing"),
                                  ("review", cmd_review, "doing -> review"),
                                  ("done", cmd_done, "-> done (warns on unchecked boxes)")]:
        p = sub.add_parser(name, help=help_text)
        p.add_argument("id")
        p.set_defaults(func=func)

    p = sub.add_parser("log", help="append a dated log entry")
    p.add_argument("id")
    p.add_argument("message")
    p.set_defaults(func=cmd_log)

    sub.add_parser("board", help="regenerate BOARD.md").set_defaults(func=cmd_board)
    sub.add_parser("validate", help="validate all task files").set_defaults(func=cmd_validate)

    p = sub.add_parser("next", help="unblocked todo tasks by priority")
    p.add_argument("--count", type=int, default=5)
    p.set_defaults(func=cmd_next)

    sub.add_parser("archive",
                   help=f"move done tasks older than {ARCHIVE_AFTER_DAYS}d to archive/"
                   ).set_defaults(func=cmd_archive)

    for name, func in [("hook-session-start", hook_session_start),
                       ("hook-post-tool-use", hook_post_tool_use),
                       ("hook-stop", hook_stop)]:
        sub.add_parser(name).set_defaults(func=func, is_hook=True)

    args = parser.parse_args()
    if getattr(args, "is_hook", False):
        try:
            sys.exit(args.func(args) or 0)
        except SystemExit:
            raise
        except Exception:
            sys.exit(0)  # hooks fail open
    sys.exit(args.func(args) or 0)


if __name__ == "__main__":
    main()
