# Centralized state definitions for all conversation handlers

# Main flow states
(
    LANGUAGE,
    CURRENCY,
    LIMIT,
    TRANSACTION,
    TX_CHOOSE_CATEGORY,
    SPECIFY_CATEGORY,
    ADD_CATEGORY,
    SETTINGS_LANGUAGE,
    SETTINGS_CURRENCY,
    SETTINGS_LIMIT,
    SELECT_RECORDS_COUNT,
    SELECT_TRANSACTION_CATEGORY,
    SELECT_TRANSACTION_SUBCATEGORY,
    ENTER_TRANSACTION_AMOUNT,
    CONFIRM_TRANSACTION,
    HANDLE_TRANSACTION_CREATE_CATEGORY,
    CATEGORY_MANAGEMENT,
    CATEGORY_EDIT,
    TASK_MANAGEMENT,
    TASK_EDIT,
    TRANSACTION_LIST, 
    TRANSACTION_EDIT, 
    EDIT_DATE, 
    EDIT_CATEGORY, 
    EDIT_SUBCATEGORY, 
    EDIT_AMOUNT, 
    CONFIRM_DELETE,
    SELECT_CATEGORIES,
    SELECT_TIME_PERIOD,
    SHOW_SUMMARY,
    SHOW_TRANSACTIONS,
    WAITING_FOR_DOCUMENT,
    PROCESS_INCOME,
    DELETE_PROFILE
) = range(34)




# Additional basic states
WAITING_FOR_DOCUMENT = 1
PROCESS_INCOME = 2
DELETE_PROFILE = 3
# List of unique states
